language: objective-c
osx_image: xcode9.3
before_install:
- pod repo update
script: xcodebuild -workspace "Processing for iOS.xcworkspace" -scheme "Processing for iOS" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
